[package]
name = "tokio-js"
version = "1.0.0"
edition = "2021"
authors = [
    "Матвей Т <github.com/AtomicGamer9523>"
]

[lib]
crate-type = ["cdylib"]

[dependencies.node-bindgen]
version = "4.0"

[build-dependencies.node-bindgen]
version = "4.0"
features = ["build"]