name: Build TokioJS

on: 
  push:
    branches:
      - release

env:
  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: release
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm i
      - run: node builder.js
      - run: npm install -g turbo
      - run: turbo build
      - run: npm run cli -- --diagnose
      - run: npm run __npmpack__
      - run: rm builder.js
      - run: npm ci

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: release
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
      - run: npm i
      - run: node builder.js
      - run: npm install -g turbo
      - run: turbo build
      - run: npm run cli -- --diagnose
      - run: npm run __npmpack__
      - run: rm builder.js
      - run: npm ci
      - run: npm publish
